version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: ai-chat-backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ai-chat-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend

